apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260606-224620-35tvdndyp0ln-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260606-224620-35tvdndyp0ln.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260606-224620-35tvdndyp0ln-service
            port:
              number: 80
